### ISSUE TITLE
コントローラを開発する_続き

### ISSUE THREAD

**Issue by mekabuhk** [kabumotohomare/hiraizumi_wifi_app#10]
# Pinコントローラに必要なアクションを整理して実装

- 一覧に関するルーティングを作成
- 地図に関するルーティングを作成
- 「報告アプリ - 報告一覧 1/2」型の「店舗一覧」画面を設計
- 共通レイアウトのダッシュボードに「店舗一覧」「地図表示画面」のリンクを設置
- 地図表示画面へのリンクはtarget_blankにする

**Comment by kabumotohomare** [comment]
そもそもDashboardを「店舗一覧」にすることにした
- 店舗一覧(=Dashboard)に関するルーティングを作成
- 地図(=ユーザーが見る画面)に関するルーティングを作成
- 共通レイアウトのナビゲーションを編集する

**Comment by kabumotohomare** [comment]
未認証の場合: ユーザーがログインしていない場合、ユーザーを地図ページにリダイレクトする
認証済みの場合: ユーザーがログインしている場合、ルートへのアクセスを許可し、管理画面に遷移する

```
Route::get('/dashboard', function () {
      return view('dashboard');
　　->name('dashboard');
```

**Comment by kabumotohomare** [comment]
地図ページ表示に関するルーティングを作成
MapDrawingController
